CREATE TYPE JOURNEY_STATUS AS ENUM ('ACTIVE', 'COMPLETE');

CREATE TABLE IF NOT EXISTS journeys  (
    id uuid UNIQUE PRIMARY KEY,
    user_id VARCHAR (50) NOT NULL,
    status JOURNEY_STATUS NOT NULL,
    lat FLOAT,
    lng FLOAT
);